/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_rule_token1 = 1,
  anon_sym_LF = 2,
  sym__normal_path = 3,
  anon_sym_DQUOTE = 4,
  aux_sym__quoted_path_token1 = 5,
  anon_sym_BSLASH = 6,
  aux_sym__quoted_path_token2 = 7,
  anon_sym_AT = 8,
  sym_user_identifier = 9,
  sym_email = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_group_name = 13,
  anon_sym_POUND = 14,
  aux_sym_comment_token1 = 15,
  aux_sym_line_without_ending_token1 = 16,
  sym_source_file = 17,
  sym_rule = 18,
  sym_path = 19,
  sym__quoted_path = 20,
  sym_owner = 21,
  sym_user_owner = 22,
  sym_group = 23,
  sym_comment = 24,
  sym_line_without_ending = 25,
  sym_line_with_ending = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_rule_repeat1 = 28,
  aux_sym__quoted_path_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_rule_token1] = "rule_token1",
  [anon_sym_LF] = "\n",
  [sym__normal_path] = "_normal_path",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__quoted_path_token1] = "_quoted_path_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym__quoted_path_token2] = "_quoted_path_token2",
  [anon_sym_AT] = "@",
  [sym_user_identifier] = "user_identifier",
  [sym_email] = "email",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_group_name] = "group_name",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_line_without_ending_token1] = "line_without_ending_token1",
  [sym_source_file] = "source_file",
  [sym_rule] = "rule",
  [sym_path] = "path",
  [sym__quoted_path] = "_quoted_path",
  [sym_owner] = "owner",
  [sym_user_owner] = "user_owner",
  [sym_group] = "group",
  [sym_comment] = "comment",
  [sym_line_without_ending] = "line_without_ending",
  [sym_line_with_ending] = "line_with_ending",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym__quoted_path_repeat1] = "_quoted_path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_rule_token1] = aux_sym_rule_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym__normal_path] = sym__normal_path,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__quoted_path_token1] = aux_sym__quoted_path_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym__quoted_path_token2] = aux_sym__quoted_path_token2,
  [anon_sym_AT] = anon_sym_AT,
  [sym_user_identifier] = sym_user_identifier,
  [sym_email] = sym_email,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_group_name] = sym_group_name,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_line_without_ending_token1] = aux_sym_line_without_ending_token1,
  [sym_source_file] = sym_source_file,
  [sym_rule] = sym_rule,
  [sym_path] = sym_path,
  [sym__quoted_path] = sym__quoted_path,
  [sym_owner] = sym_owner,
  [sym_user_owner] = sym_user_owner,
  [sym_group] = sym_group,
  [sym_comment] = sym_comment,
  [sym_line_without_ending] = sym_line_without_ending,
  [sym_line_with_ending] = sym_line_with_ending,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym__quoted_path_repeat1] = aux_sym__quoted_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_rule_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym__normal_path] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_path_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_user_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_email] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_without_ending_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_path] = {
    .visible = false,
    .named = true,
  },
  [sym_owner] = {
    .visible = true,
    .named = true,
  },
  [sym_user_owner] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_without_ending] = {
    .visible = true,
    .named = true,
  },
  [sym_line_with_ending] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__quoted_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '%' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '@') ADVANCE(9);
      if (lookahead == '%' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '@' ||
          lookahead == '[') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_rule_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__normal_path);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__normal_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__quoted_path_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__quoted_path_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_user_identifier);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_user_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_email);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_group_name);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_line_without_ending_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 31},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym__quoted_path_token2] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym_rule] = STATE(2),
    [sym_path] = STATE(4),
    [sym__quoted_path] = STATE(7),
    [sym_comment] = STATE(2),
    [sym_line_without_ending] = STATE(2),
    [sym_line_with_ending] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__normal_path] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [aux_sym_line_without_ending_token1] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym__normal_path,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      aux_sym_line_without_ending_token1,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_path,
    STATE(7), 1,
      sym__quoted_path,
    STATE(3), 5,
      sym_rule,
      sym_comment,
      sym_line_without_ending,
      sym_line_with_ending,
      aux_sym_source_file_repeat1,
  [29] = 8,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym__normal_path,
    ACTIONS(20), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(26), 1,
      aux_sym_line_without_ending_token1,
    STATE(4), 1,
      sym_path,
    STATE(7), 1,
      sym__quoted_path,
    STATE(3), 5,
      sym_rule,
      sym_comment,
      sym_line_without_ending,
      sym_line_with_ending,
      aux_sym_source_file_repeat1,
  [58] = 5,
    ACTIONS(31), 1,
      aux_sym_rule_token1,
    ACTIONS(33), 1,
      anon_sym_LF,
    STATE(6), 1,
      aux_sym_rule_repeat1,
    ACTIONS(35), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [77] = 4,
    ACTIONS(39), 1,
      aux_sym_rule_token1,
    STATE(5), 1,
      aux_sym_rule_repeat1,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(42), 3,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [94] = 5,
    ACTIONS(31), 1,
      aux_sym_rule_token1,
    ACTIONS(46), 1,
      anon_sym_LF,
    STATE(5), 1,
      aux_sym_rule_repeat1,
    ACTIONS(48), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [113] = 2,
    ACTIONS(50), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(52), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [125] = 2,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(56), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [137] = 2,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(60), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [149] = 2,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(64), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [161] = 2,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(42), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [173] = 2,
    ACTIONS(66), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(68), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [185] = 2,
    ACTIONS(70), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
    ACTIONS(72), 4,
      aux_sym_rule_token1,
      anon_sym_LF,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
  [197] = 3,
    ACTIONS(76), 1,
      anon_sym_LF,
    ACTIONS(78), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [210] = 3,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(84), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [223] = 5,
    ACTIONS(86), 1,
      anon_sym_AT,
    ACTIONS(88), 1,
      sym_email,
    ACTIONS(90), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_owner,
    STATE(9), 2,
      sym_user_owner,
      sym_group,
  [240] = 2,
    ACTIONS(94), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [250] = 2,
    ACTIONS(98), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [260] = 2,
    ACTIONS(102), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(100), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [270] = 2,
    ACTIONS(48), 2,
      sym__normal_path,
      aux_sym_line_without_ending_token1,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_POUND,
  [280] = 4,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      aux_sym__quoted_path_token1,
    ACTIONS(108), 1,
      anon_sym_BSLASH,
    STATE(23), 1,
      aux_sym__quoted_path_repeat1,
  [293] = 4,
    ACTIONS(108), 1,
      anon_sym_BSLASH,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 1,
      aux_sym__quoted_path_token1,
    STATE(21), 1,
      aux_sym__quoted_path_repeat1,
  [306] = 4,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      aux_sym__quoted_path_token1,
    ACTIONS(119), 1,
      anon_sym_BSLASH,
    STATE(23), 1,
      aux_sym__quoted_path_repeat1,
  [319] = 1,
    ACTIONS(114), 3,
      anon_sym_DQUOTE,
      aux_sym__quoted_path_token1,
      anon_sym_BSLASH,
  [325] = 1,
    ACTIONS(122), 1,
      aux_sym__quoted_path_token2,
  [329] = 1,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [333] = 1,
    ACTIONS(126), 1,
      aux_sym_comment_token1,
  [337] = 1,
    ACTIONS(128), 1,
      sym_user_identifier,
  [341] = 1,
    ACTIONS(130), 1,
      sym_group_name,
  [345] = 1,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 77,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 113,
  [SMALL_STATE(8)] = 125,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 149,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 173,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 197,
  [SMALL_STATE(15)] = 210,
  [SMALL_STATE(16)] = 223,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 250,
  [SMALL_STATE(19)] = 260,
  [SMALL_STATE(20)] = 270,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 293,
  [SMALL_STATE(23)] = 306,
  [SMALL_STATE(24)] = 319,
  [SMALL_STATE(25)] = 325,
  [SMALL_STATE(26)] = 329,
  [SMALL_STATE(27)] = 333,
  [SMALL_STATE(28)] = 337,
  [SMALL_STATE(29)] = 341,
  [SMALL_STATE(30)] = 345,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_path, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_path, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_owner, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_owner, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_path, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_path, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_owner, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user_owner, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_without_ending, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_without_ending, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_with_ending, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_with_ending, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__quoted_path_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quoted_path_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quoted_path_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [124] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_codeowners(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "codeowners",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
